name: build new md2docx-csharp
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore
      
    - name: Test
      run: dotnet test
 
    - name: Build md2docx-csharp
      run: MSBuild.exe md2docx.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: md2docx
        path: md2docx\bin\Release
